# Generated by Django 4.1.7 on 2023-03-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0010_products_inventory"),
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="products",
        ),
        migrations.AddField(
            model_name="cart",
            name="products",
            field=models.ManyToManyField(to="products.products"),
        ),
    ]
