# Generated by Django 4.1.7 on 2023-03-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0002_remove_cart_products_cart_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="colour",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="cart",
            name="size",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
