# Generated by Django 4.1.7 on 2023-03-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0004_remove_cart_colour_remove_cart_products_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="total_price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
