# Generated by Django 4.1.7 on 2023-03-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_alter_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="otp",
            field=models.IntegerField(blank=True, default="profile.svg", null=True),
        ),
    ]
