# Generated by Django 4.1.7 on 2023-03-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0008_alter_user_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="otp",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile",
            field=models.ImageField(
                blank=True, default="profile.png", null=True, upload_to=""
            ),
        ),
    ]
