# Generated by Django 4.1.7 on 2023-03-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_remove_order_status_orderitem_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("0", "Pending"),
                    ("1", "Out for delivary"),
                    ("2", "Delivered"),
                ],
                max_length=200,
                null=True,
            ),
        ),
    ]
