# Generated by Django 4.1.7 on 2023-03-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0004_alter_orderitem_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_placed",
            field=models.BooleanField(default=False),
        ),
    ]
