# Generated by Django 4.1.7 on 2023-03-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0005_order_is_placed"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_id",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
