# Generated by Django 4.1.7 on 2023-03-27 10:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0006_order_payment_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="is_placed",
            new_name="paid",
        ),
    ]
