# Generated by Django 4.1.7 on 2023-03-09 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "products",
            "0002_alter_category_created_by_alter_category_update_by_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="colour",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="products",
            name="size",
            field=models.CharField(
                choices=[
                    ("Larger", "L"),
                    ("XLL", "XXL"),
                    ("Extra Large", "XL"),
                    ("Small", "S"),
                    ("Medium", "M"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        max_length=200,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products.Section.created_by+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "update_by",
                    models.ForeignKey(
                        blank=True,
                        max_length=200,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products.Section.ipdated_by+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="products",
            name="section",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.section",
            ),
        ),
    ]
