# Generated by Django 4.1.7 on 2023-03-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_products_colour_alter_products_size_section_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="size",
            field=models.CharField(
                choices=[
                    ("Extra Large", "XL"),
                    ("Larger", "L"),
                    ("Small", "S"),
                    ("XLL", "XXL"),
                    ("Medium", "M"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
