# Generated by Django 4.1.7 on 2023-03-10 05:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_alter_products_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="multipleimage",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="products",
            name="size",
            field=models.CharField(
                choices=[
                    ("Medium", "M"),
                    ("XLL", "XXL"),
                    ("Small", "S"),
                    ("Extra Large", "XL"),
                    ("Larger", "L"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
