# Generated by Django 4.1.7 on 2023-03-13 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0006_remove_products_colour_alter_products_size_colour_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="colour",
            field=models.ManyToManyField(
                blank=True, max_length=20, to="products.colour"
            ),
        ),
        migrations.RemoveField(
            model_name="products",
            name="size",
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        max_length=200,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products.size.created_by+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "update_by",
                    models.ForeignKey(
                        blank=True,
                        max_length=200,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products.size.ipdated_by+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="products",
            name="size",
            field=models.ManyToManyField(to="products.size"),
        ),
    ]
