# Generated by Django 4.1.7 on 2023-03-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_alter_products_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="size",
            field=models.ManyToManyField(blank=True, max_length=5, to="products.size"),
        ),
    ]
