# Generated by Django 4.1.7 on 2023-03-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_alter_products_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="inventory",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
